# Generated by Django 3.2.25 on 2025-11-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(help_text="Unique identifier for the station (e.g., 'mombarone-san-carlo')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Mombarone San Carlo')", max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude coordinate', max_digits=9)),
                ('altitude', models.IntegerField(help_text='Altitude in meters above sea level')),
                ('trail_name', models.CharField(blank=True, help_text='Name of the trail this station is on', max_length=200)),
                ('installation_date', models.DateField(blank=True, help_text='Date when station was installed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this station is currently operational')),
                ('has_atmospheric', models.BooleanField(default=True, help_text='Has temperature/humidity/pressure sensor')),
                ('has_precipitation', models.BooleanField(default=True, help_text='Has rain detection sensor')),
                ('has_light', models.BooleanField(default=True, help_text='Has UV/lux sensors')),
                ('has_air_quality', models.BooleanField(default=True, help_text='Has CO2 sensor')),
                ('has_soil', models.BooleanField(default=True, help_text='Has soil moisture sensor')),
                ('has_trail_activity', models.BooleanField(default=True, help_text='Has PIR motion sensor for trail traffic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'db_table': 'stations',
                'ordering': ['station_id'],
            },
        ),
    ]
