# Generated by Django 3.2.25 on 2025-11-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailActivityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('motion_count', models.IntegerField(blank=True, help_text='Number of motion detections', null=True)),
                ('period_minutes', models.IntegerField(blank=True, help_text='Time period over which motion was counted', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_activity_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Trail Activity Reading',
                'verbose_name_plural': 'Trail Activity Readings',
                'db_table': 'trail_activity_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SoilReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('moisture_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Soil moisture percentage (0-100)', max_digits=5, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Soil Reading',
                'verbose_name_plural': 'Soil Readings',
                'db_table': 'soil_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('is_raining', models.BooleanField(blank=True, help_text="Whether it's currently raining", null=True)),
                ('rain_detected_last_hour', models.BooleanField(blank=True, help_text='Whether rain was detected in the last hour', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Precipitation Reading',
                'verbose_name_plural': 'Precipitation Readings',
                'db_table': 'precipitation_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, help_text='UV index (0-15+)', max_digits=4, null=True)),
                ('lux', models.IntegerField(blank=True, help_text='Light intensity in lux', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Light Reading',
                'verbose_name_plural': 'Light Readings',
                'db_table': 'light_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AtmosphericReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius', max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Relative humidity percentage (0-100)', max_digits=5, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=2, help_text='Atmospheric pressure in hPa', max_digits=6, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Atmospheric Reading',
                'verbose_name_plural': 'Atmospheric Readings',
                'db_table': 'atmospheric_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('co2_ppm', models.IntegerField(blank=True, help_text='CO2 concentration in parts per million', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Air Quality Reading',
                'verbose_name_plural': 'Air Quality Readings',
                'db_table': 'air_quality_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='trailactivityreading',
            index=models.Index(fields=['station', '-timestamp'], name='trail_activ_station_e990f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trailactivityreading',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='soilreading',
            index=models.Index(fields=['station', '-timestamp'], name='soil_readin_station_97ffea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='soilreading',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='precipitationreading',
            index=models.Index(fields=['station', '-timestamp'], name='precipitati_station_305bc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precipitationreading',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='lightreading',
            index=models.Index(fields=['station', '-timestamp'], name='light_readi_station_5acb12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lightreading',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='atmosphericreading',
            index=models.Index(fields=['station', '-timestamp'], name='atmospheric_station_50866a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='atmosphericreading',
            unique_together={('station', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='airqualityreading',
            index=models.Index(fields=['station', '-timestamp'], name='air_quality_station_fa1647_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='airqualityreading',
            unique_together={('station', 'timestamp')},
        ),
    ]
