# Generated by Django 3.2.25 on 2026-03-22 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityreading',
            name='aqi',
            field=models.IntegerField(blank=True, help_text='Air Quality Index 1-5 (ENS160)', null=True),
        ),
        migrations.AddField(
            model_name='airqualityreading',
            name='tvoc_ppb',
            field=models.IntegerField(blank=True, help_text='Total Volatile Organic Compounds in ppb (ENS160)', null=True),
        ),
        migrations.AddField(
            model_name='soilreading',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil temperature in Celsius (DS18B20)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='co2_ppm',
            field=models.IntegerField(blank=True, help_text='CO2 concentration in parts per million (ENS160)', null=True),
        ),
        migrations.AlterField(
            model_name='lightreading',
            name='lux',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Light intensity in lux', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When this reading was taken')),
                ('percentage', models.IntegerField(blank=True, help_text='Battery percentage (0-100)', null=True)),
                ('voltage_mv', models.IntegerField(blank=True, help_text='Battery voltage in millivolts', null=True)),
                ('is_charging', models.BooleanField(blank=True, help_text='Whether the battery is currently charging', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='stations.station')),
            ],
            options={
                'verbose_name': 'Power Reading',
                'verbose_name_plural': 'Power Readings',
                'db_table': 'power_readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='powerreading',
            index=models.Index(fields=['station', '-timestamp'], name='power_readi_station_dbc0e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='powerreading',
            unique_together={('station', 'timestamp')},
        ),
    ]
