# Generated by Django 3.2.25 on 2025-12-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('watchos', 'watchOS')], max_length=10)),
                ('bundle_id', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(blank=True, help_text='Station this device is subscribed to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station')),
            ],
            options={
                'db_table': 'device_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='device_toke_token_e218ea_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['station', 'is_active'], name='device_toke_station_6e26c8_idx'),
        ),
    ]
